#!/usr/bin/env bash

bundle install
bundle exec jekyll build --incremental

npm install -g html-minifier clean-css-cli terser
find _site -name "*.html" -exec html-minifier {} -o {} --collapse-whitespace --remove-comments --minify-css --minify-js \;
find _site -name "*.css" -exec cleancss {} -o {} \;
find _site -name "*.js" -exec terser {} -o {} -c -m \;
