#!/usr/bin/env bash

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

mkdir -p $HOME/.gem
echo <<EOF > $HOME/.gem/credentials
---
:rubygems_api_key: $RUBYGEMS_API_KEY
EOF
chmod 0600 $HOME/.gem/credentials

bundle install

TAG=$(ruby -e "puts Gem::Specification.load('$REPO.gemspec').version")
rm -rf *.gem

git fetch origin && git rev-parse v$TAG &>/dev/null && exit 1
gem build $REPO.gemspec
gem push $REPO-$TAG.gem && git tag v$TAG && git push origin --all && git push origin v$TAG
