#!/usr/bin/env bash

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

TAG=$(ruby -e "puts Gem::Specification.load('$REPO.gemspec').version")
bundle install

git fetch origin main
gem build $REPO.gemspec
gem push $REPO-$TAG.gem
